locations = ["paris", "mecca", "silicon valley", "dubai"]
print(locations)
print(sorted(locations))
print(locations)
print(sorted(locations, reverse=True))
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)
locations.sort()
print(locations)
locations.sort(reverse=True)
print(locations)
print(f"I am inviting {len(locations)} people tto the party")